### ISSUE TITLE
HasEngma requires sound occurrences not WithInventory

### ISSUE THREAD

**Issue by LinguList** [cldf/cltoolkit#26]
Reviewing the new code, which is very nice, I just found this case of HasEngma, which is a notoriously annoying feature, as it does not only require an inventory, but also the inventory's occs attribute, and the occs attribute is only available if you create the inventory from a wordlist, where it is created when checking the sounds (and sounds are later fed to the inventory for an individual language).

https://github.com/cldf/cltoolkit/blob/25705ad3226b40ca74293ab54242f6f5ec161ce7/src/cltoolkit/wordlist.py#L182-L185

Should we define this as a new class, InventoryWithOccurrences, to make sure we raise the right exception?

**Comment by LinguList** [comment]
I see your point. For me, the "tokens" aspect is clear terminology, since it is what you would need to run a lingpy analysis in some sense, that is, one that would be accepted as "tokens" in lingpy. 

But I agree that it is better to settle this and make it very transparent now. 

If I understand the linguistic terminology properly, a "grapheme" is a unit of an alphabet that may consist of more than one characters. So "sch" can also be judged to represent one grapheme. In CLDF, we argue that the Segments represent an attempt to convert the Graphemes to something else, but we do not really guarantee that they all are BIPA or another implemented transcription system. So `bipa_segments` is probably a good idea, or maybe, to allow for the theoretical possibility of having another TS than BIPA, `clts_segments`. 

This would then also call for a modification of the `sounds` and `graphemes` properties of the Form. I'd like to keep "sounds" as a property pointing to our "Sound" object, which admittedly is a CLTS sound object, but also serves as the idea of a general model of a sound.

**Comment by LinguList** [comment]
So if we say that an implemented concept in our model is a concepticon concept set, we should say that an implemented sound is a sound that can be described by a CLTS transcription system (it is unlikely people will come up with any alternative suggestions any time soon). The reason we have tokens and sounds as properties is that it is often convenient to have just one string representation of a sound, while in other situations, it is better to have access to the sounds as an object (as we can see in the feature code). 

So what do you think, @xrotwang, about having a single `Sound_Sequence` object that represents the `sounds` property of a `Form`, which consists of a sequence of `Sound` objects and has an attribute that offers the sounds as string? We need definitely both representations, and the strings are specifically important for alignments and the like. One could contrast the `sounds` then with the `graphemes`, which represent a `Grapheme_Sequence` and offers likewise access to a Grapheme in its string form and to its occurrence?

**Comment by xrotwang** [comment]
Ah, ok. I only now realize how `tokens` and `sounds` and `segments` and `graphemes` work together. I think we should only have two public attributes, a list of `Sound` objects, and a list of `Grapheme` objects. Both, `Sound` and `Grapheme` seem to already have the appropriate `__str__` method to make sure `[str(o) for o in list]` recovers what used to be ``tokens` and `segments`, right?

**Comment by LinguList** [comment]
Yes, we have this parallel of `tokens = [str(x) for x in sounds]` and `[graphemes = [str(x) for x in graphemes]`.

**Comment by LinguList** [comment]
What I'd maybe suggest now is to add two convenience properties that offer the string-sequences: `grapheme_sequence` and `sound_sequence`, which would correspond to `segments` and `tokens` respectively. Alternatively, one could use the name `grapheme_sequence` for what is by now `graphemes` and `sound_sequence` for what is now `sounds`, since Form uses functions to look both up, and `graphemes` (segments) and `sounds` (tokens) is more frequently used in many computations.

**Comment by xrotwang** [comment]
So, I'd opt to basically switch attributes and properties "tokens" and "sounds", "segments" and "graphemes" for Forms, and then drop the properties :) I'd rather have user code with `tokens = [str(x) for x in sounds]` than baking this "take an x call it y" magic into the library.

**Comment by LinguList** [comment]
There was one specific reason why the Form uses `@property` to generate the sounds instead of doing this vice-versa: the calculation of the occurrences requires a hashable object for the dictionary, and this is the `str(x)` of a Sound object. But if one can do this differently, I don't mind to change it. I'd just like to keep access to both the list of objects and the list of strings that give access to object keys as to properties of a form for both graphemes and sounds, preferably using a shorter name for the list of strings, since it will be used more often.

**Comment by xrotwang** [comment]
Hm. Ok. Then I'd propose:
Languages may not have `segmented_forms`, but `forms_with_graphemes`. And Forms have `graphemes` (list of strings) and `grapheme_objects`, and `sounds` and `sound_objects`. While this is clunky, it at least makes the API raise proper expectations.

**Comment by xrotwang** [comment]
This clunkier, but more transparent nomenclature will also make it simpler to have consistent naming for the requirements.

**Comment by LinguList** [comment]
Yes. This sounds good to me! And I prefer it over my "X_sequence" suggestion, which is not explicit at all.

**Comment by xrotwang** [comment]
Ok, so `bipa_forms` will be replace by `forms_with_sounds`, too, right?

**Comment by LinguList** [comment]
Yes!
