### ISSUE TITLE
Tilde not recognized as sound

### ISSUE THREAD

**Issue by FredericBlum** [cldf/cltoolkit#31]
@xrotwang @LinguList In some datasets, we have started using a tilde representing a floating nasality feature, corresponding to nasal consonants in other languages. However, this is not recognized by the `syllable_complexity` function from cltoolkit/features/phonology (line 419), crashing the lexibank 2.0 conversion. . What would be the best way to work around this issue?

**Comment by LinguList** [comment]
Ah, mier...coles. This is a rather fundamental issue with CLTS, since we handle the model as a MARKER, but strictly speaking, it is a sound (that is: `bipa["∼"]`).

**Comment by LinguList** [comment]
I think we must modify `"∼"` in CLTS in a new version, and model it as a sound, just a consonant, like a nasal.

**Comment by LinguList** [comment]
What I do not understand, however, is, how the code can break.

**Comment by LinguList** [comment]
Check this line 

https://github.com/cldf/cltoolkit/blob/10c2692bd5370d042fc70494a0b948fea8e6a58d/src/cltoolkit/features/phonology.py#L436C1-L436C79
```
            sounds_in_form = [s for s in form.sound_objects if s.type != "marker"]
```
It means, that every tilde-like symbol is just DELETED from the data. This should not result in an error, right?

**Comment by LinguList** [comment]
Because `bipa["∼"].type` is `marker`.

**Comment by FredericBlum** [comment]
I think I found the problem. We need to move `idx +=1` within the scope of sounds_in_form. Let's look at the code:

```
    for form in forms_with_sounds:
        idx = 0
        sounds_in_form = [s for s in form.sound_objects if s.type != "marker"]
        for i, syllable in enumerate(iter_syllables(form)):
            sounds, count = [], 0
            sounds_in_syllable = []
            for token in syllable:
                sounds_in_syllable += [sounds_in_form[idx]]
                idx += 1
```

Currently, the `idx+=1` gets computed while iterating over the elements within `form`, not within `sounds_in_form`. That means that markers are included here, and get an index assigned. So if we have a toy example of: `['a', '~', 'u']`, the `u` is already has `idx=2` (third element in `form`), but `sounds_in_form` only has `['a', 'u']`. So once we check for `sounds_in_form[idx]`, we get an index error _after_ the tilde.

I will set up a fix, re-run the conversion, and open a PR if this indeed fixes the problem - but I think it will.

**Comment by FredericBlum** [comment]
@LinguList @xrotwang I will add the PR once I get the necessary rights within the repository.

**Comment by LinguList** [comment]
Yes, that looks like a very obvious and clear bug. But be aware of one thing here: The tilde is classified as a marker in CLTS, but it is treated as a NASAL sound by LingPy's syllabification method.

**Comment by LinguList** [comment]
The `iter_syllables` method will already correctly treat the tilde as a Nasal, just as I said, but since `sounds_in_form` excludes it, since CLTS says it is a `marker`, we get the discrepancy in the indices.

**Comment by LinguList** [comment]
So a fix that just LEAVES the tilde in the list of sounds, would just do that. The index itself must not be touched in my impression.
